# -*- coding: utf-8 -*-
"""Automatic Tools .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BRAmBrjFyAnoprSLU9paGQleniA22mTD
"""

#Tools for Automatic EDA operation
#ydata-profiling:It tells data anlysis in automatically

import pandas as pd
#!pip install ydata-profiling
from ydata_profiling import ProfileReport
data = pd.read_csv('adult.csv')
profile = ProfileReport(data, title="Pandas Profiling Report")
profile.to_notebook_iframe()



from typeguard import install_import_hook
#Auto Viz:Automatic Visulazation
#!pip install autoviz
from autoviz.AutoViz_Class import AutoViz_Class
AV = AutoViz_Class()
data = pd.read_csv('adult.csv')

AV.AutoViz(
    filename = 'adult.csv',
    sep = ",",
    depVar = "Income",
    dfte = data)

#!pip uninstall sweetviz
import pandas as pd
import sweetviz as sv
data = pd.read_csv('adult.csv')
report = sv.analyze(data)
report.show_html("sweetviz_report.html")