# -*- coding: utf-8 -*-
"""EDA Project_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1290waVSI9OQi5Cyq2bqwJPPkQaqkyFVo
"""

import pandas as pd
df=pd.read_csv('/content/adult.csv')

print(df.head(5))
print(df.tail(5))
print(df.info())
print(df.describe())
print(df.shape)
print(df.dtypes)
print(df.columns)
#Data Cleaning
print(df.isna().sum())
#Data Duplicated
#print(df.duplicated())
#print(df.drop_duplicates())
#print(df.duplicated().sum())

#Viewing and Filtering
# 1. Select the age column

print(df['Age'])
# 2. Select age, education, occupation and income columns

print(df[['Age', 'Education', 'Occupation', 'Income']])

# 3. Display first 10 rows using iloc

print(df.iloc[0:10])
# 4. Select rows 10 to 20 and age, education columns

print(df.loc[10:20, ['Age', 'Education']])

# 5. Filter people whose age is greater than 50

print(df[df['Age'] > 50])
# 6. Filter people whose income is >50K

print(df[df['Income'] == '>50K'])

# 7. Age > 40 AND hours-per-week > 40

print(df[(df['Age'] > 40) &(df['Hours per Week'] > 40)])

# 8. Education is Bachelors OR Masters

print(df[df['Education'].isin([' Bachelors', 'Masters']) ])

# 9. Mean, Median, Minimum and Maximum Age

print(df['Age'].agg(['mean','median','min','max']))

# 10. Standard deviation of age and hours-per-week

print(
    df[['Age', 'Hours per Week']].agg(['std']))

# 11. Statistical summary of numerical columns

print(
    df.select_dtypes(include='number').agg([
        'count',
        'mean',
        'median',
        'min',
        'max',
        'std'
    ]))

# 12. Number of unique education values
# and frequency of each education category

print(
    "Unique Education Values:",
    df['Education'].nunique()
)

print(
    df['Education'].value_counts())

# 13. Number of people in each income category

print(df['Income'].value_counts())

# 14. Percentage of people in each income category

#percentage = (income_count / np.sum(income_count)) * 100
print(
    df['Income'].value_counts(normalize=True ) * 100)

# 15. Statistical analysis of hours-per-week
#     for people earning >50K

print(
    df[
        df['Income'] == '>50K'
    ]['Hours per Week'].agg([
        'count',
        'mean',
        'median',
        'min',
        'max',
        'std'
    ]))


# 16. Statistical analysis of age
#     for people with Bachelors education

print(
    df[
        df['Education'] == ' Bachelors']['Age'].agg([
        'count', 'mean', 'median', 'min', 'max', 'std']))

# 17. Youngest and oldest person

print(df['Age'].agg([
        'min','max']))


# 18. Correlation between numerical columns


print(df.corr(numeric_only=True))

# 19. Correlation between age and hours-per-week


print(df[['Age', 'Hours per Week']].corr())

# 20. Most common education and occupation

print(
    "Education Mode:",
    df['Education'].mode()[0]
)

print(
    "Occupation Mode:",
    df['Occupation'].mode()[0]
)







df=(df.replace(' ?',None))
print(df.isna().sum())
df['Workclass'] = df['Workclass'].fillna('Unknow')
print(df)
df['Occupation'] = df['Occupation'].fillna('Unknow')
print(df)
df['Occupation'] =df['Occupation'].fillna('Unknow')
print(df)
df['Native Country']=df['Native Country'].fillna('Unknow')
print(df)
print(df.isna().sum())
#print(df.dropna())

#Duplicated

df=df.drop_duplicates()
print(df)
print(df.duplicated().sum())

#Inconcistance
print(df.head())
df['Workclass'] = df['Workclass'].str.strip().str.title()
print(df)
df['Education'] = df['Education'].str.strip().str.title()
print(df.head())
df['Marital Status'] = df['Marital Status'].str.strip().str.title()
print(df.head())

df['Occupation'] = df['Occupation'].str.strip().str.title()
print(df.head())

df['Relationship'] = df['Relationship'].str.strip().str.title()
print(df.head())

df['Race'] = df['Race'].str.strip().str.title()
print(df.head())

df['Gender'] = df['Gender'].str.strip().str.title()
print(df.head())

#Back Filled:For Example we have numbers and null value like this:101,102,None,104,105
#In back filled the value will assign like this:101,102,104,104,104
print(df.head(5))
df['Age'] = df['Age'].bfill()

#Forwad Filled:101,102,None,104,105
#Forwad  filled the value will assign like this:101,102,102,104,105
df['Age'] = df['Age'].ffill()

#Interchange :101,102,None,104,105
#Inter change means next value of none the value will assign like this:101,102,103,103,104
df['Age'] = df['Age'].interpolate()
print(df['Age'])

#Detcing Outliers:
#Outliers:It is a tells about far away from the point either it be a lower or upper
from numpy import quantile
Q1 = df['Age'].quantile(0.25)
Q3 = df['Age'].quantile(0.75)
IQR = Q3 - Q1
lower_bond = Q1 - 1.5 * (IQR)  #Lower bonds it will be less than that of number  it be outlier #we are finding least values #so we use - symbol
upper_bond = Q3 + 1.5 * (IQR)  #upper bond it will be greater  than of number it be outlier #we are finding least values #so we use - symbol
print(lower_bond)
print(upper_bond)

#Identify IQR Outliers
iqr_outliers = df[
    (df['Age'] < lower_bond) |
    (df['Age'] > upper_bond)
]

print("IQR Outliers:",len(iqr_outliers)) #142 outliers  will be detect

from scipy.stats import zscore
from scipy.stats.mstats import zscore

#Z- Score Method : It is a method which will detect the outliers  we want excute exact value it detect > less than value will be outliers
from scipy.stats import zscore


df['Age_zscore'] = zscore(df['Age'])

z_outliers = df[
    df['Age_zscore'].abs() > 3

]
print("Z- Scroe Outliers:",len(z_outliers))



#z-Score Triming
#---------------
df_trimmed = df[df['Age_zscore'].abs() <= 3]
print(df_trimmed)

#5.Winsorization:It be limts it shows the in between 0 to 0.3
from scipy.stats.mstats import winsorize
df['Age_winsorized'] = winsorize(
    df['Age'],
    limits = [0,0.3])
print(df.head())

#Decting outliers bounds(lower and upper)
Q1 = df['EducationNum'].quantile(0.25)
Q3 = df['EducationNum'].quantile(0.75)
IQR = Q3 - Q1
lower_bond = (Q1 - 1.5 * IQR)
upper_bond = (Q3 + 1.5 * IQR)
print(lower_bond)
print(upper_bond)




#Identify IQR Outliers
iqr_outliers = df[
    (df['Age']< lower_bond) |
    (df['Age'] > upper_bond)

]
print("IQR Ouliers:",len(iqr_outliers))

#Z- Score Method : It is a method which will detect the outliers  we want excute exact value it detect > less than value will be outliers

from scipy.stats import zscore



df['EducationNum_zscore'] = zscore(df['EducationNum'])

z_outliers = df[
    df['EducationNum_zscore'].abs() > 2
]
print("z- Score Ouliers:",len(z_outliers))

df_trimmed = df[df['EducationNum_zscore'].abs() <= 2]
print(df_trimmed)

#5.Winsorization:It be limts it shows the in between 0 to 0.3
# from scipy.stats.mstats import winsorize
# df['Age_winsorized'] = winsorize(
#     df['Age'],
#     limits = [0,0.3])
# print(df.head())

df['EducationNum_winsorized'] = winsorize(
    df['EducationNum'],
    limits = [0,0.4]
)
print(df.head())

from autoviz import AutoViz_Class
data=pd.read_csv('adult.csv')
AV = AutoViz_Class()
AV.AutoViz(
    filename = "adult.csv", # Keep filename for Autoviz internal use if it needs to access the file directly
    sep = ",",
    depVar = "Income",
    dfte = data # Use the already loaded DataFrame 'df'
)

# AV = AutoViz_Class()
# AV.AutoViz(
#     filename = "adult.csv", # Keep filename for Autoviz internal use if it needs to access the file directly
#     sep = ",",
#     depVar = "Income",
#     dfte = data, # Use the already loaded DataFrame 'df'
#     format = 'png'
# )





#Visulazation
import matplotlib.pyplot as plt
#I want Comapre Education wise age
x=df['Education']
y=df['Age']

plt.bar(x,y)
plt.title('Education VS Age')
plt.xlabel('Education')
plt.ylabel('Age')
plt.show()



#Scatter Plot:Relationship between two numerical variables
EducationNum=df['EducationNum']
Hours_per_week=df['Hours per Week']
plt.scatter(EducationNum,Hours_per_week)
plt.title('EducationNum Vs Hours_per_week')
plt.xlabel('EducationNum')
plt.ylabel('Hours_per_week')
plt.show()
print(df.head(5))

#
print(df.head())
#Pie chart:
x=df['EducationNum']
y=df['Gender']

plt.pie(x,labels=y,autopct='%1.1f%%') #autopct:which used to generate automatic percentage
plt.title('Age wise Gender')
plt.show()

#Stem Plot:It is a Statistical plot displays individual data values using vertical or hozoiontal
Final_Weight = df['Final Weight']
plt.stem(Final_Weight )
plt.title('Final Weight ')
plt.xlabel('Final Weight')

x=df['EducationNum']
y=df['Gender']
plt.plot(x,y,marker = "o") #autopct:which used to generate automatic percentage
plt.title('Age wise Gender')
plt.show()



#Box Plot:It is a Statistical plot displays individual data values using vertical or hozoiontal
Age = df['Age']
plt.boxplot(Age)
plt.title('Age Individual Data ')
plt.xlabel('Age')